/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResumenRouteImport } from './routes/_authenticated.resumen'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated.productos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated.inicio'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated.equipo'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated.configuracion'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated.chats'
import { Route as AuthenticatedAutomatizacionesRouteImport } from './routes/_authenticated.automatizaciones'
import { Route as AuthenticatedAltaClienteRouteImport } from './routes/_authenticated.alta-cliente'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumenRoute = AuthenticatedResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomatizacionesRoute =
  AuthenticatedAutomatizacionesRouteImport.update({
    id: '/automatizaciones',
    path: '/automatizaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAltaClienteRoute =
  AuthenticatedAltaClienteRouteImport.update({
    id: '/alta-cliente',
    path: '/alta-cliente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alta-cliente': typeof AuthenticatedAltaClienteRoute
  '/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alta-cliente': typeof AuthenticatedAltaClienteRoute
  '/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/alta-cliente': typeof AuthenticatedAltaClienteRoute
  '/_authenticated/automatizaciones': typeof AuthenticatedAutomatizacionesRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/alta-cliente'
    | '/automatizaciones'
    | '/chats'
    | '/clientes'
    | '/configuracion'
    | '/crm'
    | '/equipo'
    | '/inicio'
    | '/productos'
    | '/resumen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/alta-cliente'
    | '/automatizaciones'
    | '/chats'
    | '/clientes'
    | '/configuracion'
    | '/crm'
    | '/equipo'
    | '/inicio'
    | '/productos'
    | '/resumen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agenda'
    | '/_authenticated/alta-cliente'
    | '/_authenticated/automatizaciones'
    | '/_authenticated/chats'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracion'
    | '/_authenticated/crm'
    | '/_authenticated/equipo'
    | '/_authenticated/inicio'
    | '/_authenticated/productos'
    | '/_authenticated/resumen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumen': {
      id: '/_authenticated/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof AuthenticatedResumenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automatizaciones': {
      id: '/_authenticated/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AuthenticatedAutomatizacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alta-cliente': {
      id: '/_authenticated/alta-cliente'
      path: '/alta-cliente'
      fullPath: '/alta-cliente'
      preLoaderRoute: typeof AuthenticatedAltaClienteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAltaClienteRoute: typeof AuthenticatedAltaClienteRoute
  AuthenticatedAutomatizacionesRoute: typeof AuthenticatedAutomatizacionesRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedResumenRoute: typeof AuthenticatedResumenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAltaClienteRoute: AuthenticatedAltaClienteRoute,
  AuthenticatedAutomatizacionesRoute: AuthenticatedAutomatizacionesRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedResumenRoute: AuthenticatedResumenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
